language: c

addons:
  apt:
    update: true
    packages:
      - make
      - libtool
      - pkg-config
      - autoconf
      - texinfo
      - gcc-arm-linux-gnueabihf

before_install:
    - sudo apt-get install -y gcc-arm-linux-gnueabihf
    - sudo apt-get install bc
    - export TRAVIS_COMPILER=arm-linux-gnueabihf-
    - export CC=arm-linux-gnueabihf-


install:
    - gem install --no-ri --no-rdoc fpm

script:
    - ./make_deb.sh

# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: '*.deb'
#   file_glob: true
#   skip_cleanup: true
#   name: $TRAVIS_TAG
#   on:
#     branch: master
# tags: true
