language: c

addons:
  apt:
    update: true
    packages:
      - make
      - libtool
      - pkg-config
      - autoconf
      - texinfo
      - gcc-arm-linux-gnueabihf

env:
    - COMPILER=gcc-arm-linux-gnueabihf

install:
  - gem install --no-ri --no-rdoc fpm

script:
  - ./make_deb.sh

# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: '*.deb'
#   file_glob: true
#   skip_cleanup: true
#   name: $TRAVIS_TAG
#   on:
#     branch: master
# tags: true
