language: c

addons:
  apt:
    update: true
    packages:
      - make
      - libtool
      - pkg-config
      - autoconf
      - texinfo
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf


install:
    - gem install --no-ri --no-rdoc fpm

script:
    - export ARCH=arm
    - export CROSS_COMPILE=arm-linux-gnueabihf-gcc-4.8
    - export TRAVIS_COMPILER=arm-linux-gnueabihf-gcc-4.8
    - export CC=arm-linux-gnueabihf-gcc-4.8
    - ./make_deb.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: '*.deb'
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    branch: master
tags: true
