language: cpp

addons:
  apt:
    update: true
    packages:
      - make
      - libtool
      - pkg-config
      - autoconf
      - texinfo
      - gcc-arm-linux-gnueabihf
      - g++-arm-linux-gnueabihf
      - qemu-system-arm
      - qemu-user-static

env: QEMU_INTERPRETER=qemu-arm-static CC_COMPILER=arm-linux-gnueabihf-gcc CXX_COMPILER=arm-linux-gnueabihf-g++


install:
  - gem install --no-ri --no-rdoc fpm

script:
  - ./make_deb.sh

# deploy:
#   provider: releases
#   api_key: $GITHUB_TOKEN
#   file: '*.deb'
#   file_glob: true
#   skip_cleanup: true
#   name: $TRAVIS_TAG
#   on:
#     branch: master
# tags: true
